test(add-missing-tests): add the missing tests to improve code coverage
apimatic/okhttp-client-adapter pull request #14
Opened 2022-10-25 07:10 UTC by hamzashoukat94

OkHttp-client-adapter is responsible for making client request to the server. This should be error-free and should work fine and smoothly. So, added the missing tests to improve the code coverage.

closes #5

2022-10-25 14:02 UTC, sufyankhanrao commented on src/test/java/apimatic/okhttpclient/adapter/OkClientTest.java
> +import static org.mockito.Mockito.doThrow;
This import is unused so it should be removed.

2022-10-25 14:12 UTC, sufyankhanrao requested changes
Above mentioned comments need resolution.

2022-10-25 15:05 UTC, hamzashoukat94 commented on src/test/java/apimatic/okhttpclient/adapter/OkClientTest.java
> +import static org.mockito.Mockito.doThrow;
Yes, It is removed now

2022-10-25 15:13 UTC, hamzashoukat94 commented on src/main/java/io/apimatic/okhttpclient/adapter/OkClient.java
>                  multipartBuilder.addPart(wrapperHeadersBuilder.build(), body);
Thanks for pointing it out. I checked that because there is a possibility that Parameters can contain the simple object (meaning neither MultipartFile instance nor Multipart instance). Reverting it back.

2022-10-25 15:14 UTC, hamzashoukat94 commented on src/main/java/io/apimatic/okhttpclient/adapter/OkClient.java
>                  multipartBuilder.addPart(wrapperHeadersBuilder.build(), body);
Reverted

2022-10-25 20:45 UTC, sufyankhanrao commented on src/main/java/io/apimatic/okhttpclient/adapter/OkClient.java
>                  multipartBuilder.addPart(wrapperHeadersBuilder.build(), body);
Is there a test case for this branch coverage (i.e. the else block)?

2022-10-26 05:29 UTC, hamzashoukat94 commented on src/main/java/io/apimatic/okhttpclient/adapter/OkClient.java
>                  multipartBuilder.addPart(wrapperHeadersBuilder.build(), body);
Test case is added now

2022-10-26 09:55 UTC, sufyankhanrao commented on src/main/java/io/apimatic/okhttpclient/adapter/OkClient.java
>                  multipartBuilder.addPart(wrapperHeadersBuilder.build(), body);
alright

2022-10-26 09:56 UTC, sufyankhanrao approved these changes
Changes look good to me.

2022-10-26 10:04 UTC, merged